export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const CATEGORY_FAILED = 'CATEGORY_FAILED';
export const ADD_CATEGORY = 'ADD_CATEGORY';

export const CATEGORY_PRODUCT_LOADING = 'CATEGORY_PRODUCT_LOADING';
export const CATEGORY_PRODUCT_FAILED = 'CATEGORY_PRODUCT_FAILED';
export const ADD_CATEGORY_PRODUCT = 'ADD_CATEGORY_PRODUCT';